# Generated by Django 3.0.1 on 2019-12-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('aname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('apsw', models.CharField(blank=True, max_length=45, null=True)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
                ('lname', models.CharField(blank=True, max_length=45, null=True)),
                ('dept', models.CharField(blank=True, max_length=45, null=True)),
                ('psn', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('gname', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('accountpicture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountgroup',
            fields=[
                ('groupname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('fixturepermission', models.IntegerField(blank=True, null=True)),
                ('accountpermission', models.IntegerField(blank=True, null=True)),
                ('emailpermission', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accountgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('dataid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'datatable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dbinfo',
            fields=[
                ('dbinfoname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dbinfovalue', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('fixtureno', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('modelpn', models.CharField(blank=True, max_length=300, null=True)),
                ('modelname', models.CharField(blank=True, max_length=300, null=True)),
                ('station', models.CharField(blank=True, max_length=300, null=True)),
                ('pmddate', models.DateTimeField(blank=True, null=True)),
                ('usagelimit', models.IntegerField(blank=True, null=True)),
                ('usagecount', models.IntegerField(blank=True, null=True)),
                ('adddate', models.DateTimeField(blank=True, null=True)),
                ('addby', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('te', models.CharField(blank=True, max_length=45, null=True)),
                ('fwidth', models.IntegerField(blank=True, null=True)),
                ('fheight', models.IntegerField(blank=True, null=True)),
                ('fdeep', models.IntegerField(blank=True, null=True)),
                ('fixturepicture', models.TextField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=45, null=True)),
                ('productionline', models.CharField(blank=True, max_length=45, null=True)),
                ('storagemode', models.IntegerField(blank=True, null=True)),
                ('pmperiodday', models.IntegerField(blank=True, null=True)),
                ('fcost', models.IntegerField(blank=True, null=True)),
                ('fcosttype', models.IntegerField(blank=True, null=True)),
                ('fixturegroup', models.CharField(blank=True, max_length=45, null=True)),
                ('pmperiodmonth', models.IntegerField(blank=True, null=True)),
                ('uutcount', models.IntegerField(blank=True, null=True)),
                ('pmlistid', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisdate', models.DateTimeField(blank=True, null=True)),
                ('histype', models.IntegerField(blank=True, null=True)),
                ('hisstatus', models.IntegerField(blank=True, null=True)),
                ('hisdetail', models.CharField(blank=True, max_length=4000, null=True)),
                ('hisfixtureid', models.CharField(blank=True, max_length=45, null=True)),
                ('hisaccountid', models.CharField(blank=True, max_length=45, null=True)),
                ('hisaccountgroup', models.CharField(blank=True, max_length=45, null=True)),
                ('hisdataaccount', models.CharField(blank=True, max_length=45, null=True)),
                ('hispmduedate', models.DateTimeField(blank=True, null=True)),
                ('hislocation', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PicAccount',
            fields=[
                ('aname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('accountpicture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pic_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PicFixture',
            fields=[
                ('fixtureno', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('fixturepicture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pic_fixture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pmissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmlistid', models.IntegerField()),
                ('pmissue', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pmissue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pmlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmlist', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pmlist',
                'managed': False,
            },
        ),
    ]
